Tareas/alumnos/grails-app/domain/com/itesm/grails/alumnos/Campus.groovy
package com.itesm.grails.alumnos

class Campus {

	String siglas,nombreCampus
	static hasMany = [students: Student]

    static constraints = {
    	siglas(unique:true,blank:false,nullable:false,maxSize:5, minSize: 5)
    	nombreCampus(blank:false,nullable:false)
    }

    String toString(){
    	return nombreCampus+" - "+siglas;
    }
}

Tareas/alumnos/grails-app/controllers/com/itesm/grails/alumnos/CampusController.groovy
package com.itesm.grails.alumnos

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class CampusController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Campus.list(params), model:[campusCount: Campus.count()]
    }

    def show(Campus campus) {
        respond campus
    }

    def create() {
        respond new Campus(params)
    }

    @Transactional
    def save(Campus campus) {
        if (campus == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (campus.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond campus.errors, view:'create'
            return
        }

        campus.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'campus.label', default: 'Campus'), campus.id])
                redirect campus
            }
            '*' { respond campus, [status: CREATED] }
        }
    }

    def edit(Campus campus) {
        respond campus
    }

    @Transactional
    def update(Campus campus) {
        if (campus == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (campus.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond campus.errors, view:'edit'
            return
        }

        campus.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'campus.label', default: 'Campus'), campus.id])
                redirect campus
            }
            '*'{ respond campus, [status: OK] }
        }
    }

    @Transactional
    def delete(Campus campus) {

        if (campus == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        campus.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'campus.label', default: 'Campus'), campus.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'campus.label', default: 'Campus'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    String toString() {
        return "Campus";
    }
}

Tareas/alumnos/grails-app/views/campus/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'campus.label', default: 'Campus')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-campus" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-campus" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.campus}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.campus}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <f:all bean="campus"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

Tareas/alumnos/grails-app/views/campus/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'campus.label', default: 'Campus')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-campus" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-campus" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.campus}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.campus}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.campus}" method="PUT">
                <g:hiddenField name="version" value="${this.campus?.version}" />
                <fieldset class="form">
                    <f:all bean="campus"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

Tareas/alumnos/grails-app/views/campus/index.gsp
<%@ page import="com.itesm.grails.alumnos.Student"%>
<%@ page import="com.itesm.grails.alumnos.Campus"%>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'campus.label', default: 'Campus')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-campus" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-campus" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            
            <!--<f:table collection="${campusList}" />-->


            <div id="list-career" class="content scaffold-list" role="main">
                <h1>Lista de campus</h1>
                <table>
                    <thead>
                        <tr>
                            <th>Siglas</th>
                            <th>Nombre del Campus</th>
                            <th>Estudiantes</th>
                        </tr>
                    </thead>
                    <tbody>
                        <g:each in="${Campus.list()}" status="i" var="campus">
                            <g:if test="${campus.id%2 == 0}">
                                <tr class="even">
                                    <td>
                                    <g:link action="show" id="${campus.id}">${campus.siglas}</g:link>
                                    </td> 
                                    <td>${campus.nombreCampus}</td>
                                    <td>
                                        <ul>
                                            <g:each in="${campus.students}" status="j" var="student">
                                                <li>
                                                    <g:link controller="student" action="show" id="${student.id}">${student}</g:link>
                                                </li>
                                            </g:each>
                                        </ul>
                                    </td>
                                </tr>
                            </g:if>
                            <g:else>
                                <tr class="odd">
                                   <td>
                                   <g:link action="show" id="${campus.id}">${campus.siglas}</g:link>
                                   </td> 
                                   <td>${campus.nombreCampus}</td>
                                   <td>
                                       <ul>
                                           <g:each in="${campus.students}" status="j" var="student">
                                               <li>
                                                   <g:link controller="student" action="show" id="${student.id}">${student}</g:link>
                                               </li>
                                           </g:each>
                                       </ul>
                                   </td>  
                                </tr>
                            </g:else>
                        </g:each>
                    </tbody>
                </table>
            </div>

            <div class="pagination">
                <g:paginate total="${campusCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

Tareas/alumnos/grails-app/views/campus/show.gsp
<%@ page import="com.itesm.grails.alumnos.Student"%>

<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'campus.label', default: 'Campus')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-campus" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-campus" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="campus" />
            <g:form resource="${this.campus}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.campus}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>