Tareas/alumnos/grails-app/domain/com/itesm/grails/alumnos/Career.groovy
package com.itesm.grails.alumnos

class Career {

	String siglas,nombreCarrera
	int programa
	static hasMany = [students: Student]

    static constraints = {
    	siglas(unique:true,blank:false,nullable:false,maxSize:3, minSize: 3)
    	nombreCarrera(blank:false,nullable:false)
    	programa(blank:false,nullable:false,min:1990, max: 3000)
    }

    String toString(){
    	return nombreCarrera+" - "+siglas;
    }
}

Tareas/alumnos/grails-app/controllers/com/itesm/grails/alumnos/CareerController.groovy
package com.itesm.grails.alumnos

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class CareerController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Career.list(params), model:[careerCount: Career.count()]
    }

    def show(Career career) {
        respond career
    }

    def create() {
        respond new Career(params)
    }

    @Transactional
    def save(Career career) {
        if (career == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (career.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond career.errors, view:'create'
            return
        }

        career.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'career.label', default: 'Career'), career.id])
                redirect career
            }
            '*' { respond career, [status: CREATED] }
        }
    }

    def edit(Career career) {
        respond career
    }

    @Transactional
    def update(Career career) {
        if (career == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (career.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond career.errors, view:'edit'
            return
        }

        career.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'career.label', default: 'Career'), career.id])
                redirect career
            }
            '*'{ respond career, [status: OK] }
        }
    }

    @Transactional
    def delete(Career career) {

        if (career == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        career.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'career.label', default: 'Career'), career.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'career.label', default: 'Career'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Tareas/alumnos/grails-app/views/career/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'career.label', default: 'Carrera')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-career" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-career" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.career}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.career}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <!--<f:all bean="career"/>-->
                    <div class="fieldcontain required">
                        <label>Siglas: <label>
                        <g:textField name="siglas" id="siglas" value="${career.siglas}" min="3" max="3" maxlength="3"/>
                    </div>

                    <div class="fieldcontain required">
                        <label>Nombre de la carrera: <label>
                        <g:textField name="nombreCarrera" id="nombreCarrera" value="${career.nombreCarrera}" />
                    </div>

                    <div class="fieldcontain required">
                        <label>Programa: <label>
                        <g:textField type="number"   name="programa" id="programa" value="${career.programa}" min="1980" max="3000" maxlength="4"/>
                    </div>

                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

Tareas/alumnos/grails-app/views/career/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'career.label', default: 'Carrera')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-career" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-career" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.career}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.career}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.career}" method="PUT">
                <g:hiddenField name="version" value="${this.career?.version}" />
                <div class="fieldcontain required">
                    <label>Siglas: <label>
                    <g:textField name="siglas" id="siglas" value="${career.siglas}" min="3" max="3" maxlength="3"/>
                </div>

                <div class="fieldcontain required">
                    <label>Nombre de la carrera: <label>
                    <g:textField name="nombreCarrera" id="nombreCarrera" value="${career.nombreCarrera}" />
                </div>

                <div class="fieldcontain required">
                    <label>Programa: <label>
                    <g:textField type="number"   name="programa" id="programa" value="${career.programa}" min="1980" max="3000" maxlength="4"/>
                </div>
                
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

Tareas/alumnos/grails-app/views/career/index.gsp
<%@ page import="com.itesm.grails.alumnos.Student"%>
<%@ page import="com.itesm.grails.alumnos.Career"%>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'career.label', default: 'Carrera')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-career" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-career" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <!--<f:table collection="${careerList}" />-->
            <!-- Solo se quito por los formatos feos que ponía al año-->

            <div id="list-career" class="content scaffold-list" role="main">
                <h1>Lista de carreras</h1>
                <table>
                    <thead>
                        <tr>
                            <th>Siglas</th>
                            <th>Nombre Carrera</th>
                            <th>Programa</th>
                            <th>Estudiantes</th>
                        </tr>
                    </thead>
                    <tbody>
                        <g:each in="${Career.list()}" status="i" var="career">
                            <g:if test="${career.id%2 == 0}">
                                <tr class="even">
                                    <td>
                                    <g:link action="show" id="${career.id}">${career.siglas}</g:link>
                                    </td> 
                                    <td>${career.nombreCarrera}</td>
                                    <td>${career.programa}</td>
                                    <td>
                                        <ul>
                                            <g:each in="${career.students}" status="j" var="student">
                                                <li>
                                                    <g:link controller="student" action="show" id="${student.id}">${student}</g:link>
                                                </li>
                                            </g:each>
                                        </ul>
                                    </td>
                                </tr>
                            </g:if>
                            <g:else>
                                <tr class="odd">
                                   <td>
                                   <g:link action="show" id="${career.id}">${career.siglas}</g:link>
                                   </td> 
                                   <td>${career.nombreCarrera}</td>
                                   <td>${career.programa}</td>
                                   <td>
                                       <ul>
                                           <g:each in="${career.students}" status="j" var="student">
                                               <li>
                                                   <g:link controller="student" action="show" id="${student.id}">${student}</g:link>
                                               </li>
                                           </g:each>
                                       </ul>
                                   </td>  
                                </tr>
                            </g:else>
                        </g:each>
                    </tbody>
                </table>
            </div>

            <div class="pagination">
                <g:paginate total="${careerCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

Tareas/alumnos/grails-app/views/career/show.gsp
<%@ page import="com.itesm.grails.alumnos.Student"%>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'career.label', default: 'Carreras')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-career" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-career" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <!--<f:display bean="career" />-->
            <ol class="property-list career"/>
                <li class="fieldcontain">
                    <span id="siglas-label" class="property-label">Siglas:</span>
                    <div class="property-value" aria-labelledby="siglas-label">${career.siglas}</div>
                </li>
                <li class="fieldcontain">
                    <span id="nombre-label" class="property-label">Nombre de la carrera:</span>
                    <div class="property-value" aria-labelledby="nombre-label">${career.nombreCarrera}</div>
                </li>
                <li class="fieldcontain">
                    <span id="programa-label" class="property-label">Programa:</span>
                    <div class="property-value" aria-labelledby="programa-label">${career.programa}</div>
                </li>
                <li class="fieldcontain">
                    <span id="alumnos-label" class="property-label">Alumnos:</span>
                    <div class="property-value" aria-labelledby="alumnos-label">
                        <g:each in="${career.students}" status="i" var="estudiante">
                            <ul>
                                <li>
                                    <g:link controller="student" action="show" id="${estudiante.id}">${estudiante}</g:link>
                                </li>
                            </ul>
                        </g:each>
                    </div>
                </li>
            </ol>
            <g:form resource="${this.career}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.career}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>