Tareas/alumnos/grails-app/domain/com/itesm/grails/alumnos/Student.groovy
package com.itesm.grails.alumnos

class Student {

	String matricula,nombreCompleto,direccion,correoElectronico;
	Career career;
	Campus campus;

    static constraints = {
    	matricula(blank:true,nullable:true)
    	nombreCompleto(blank:false,nullable:false,maxSize:750, minSize: 20)
    	direccion(blank:false,nullable:false,maxSize:150, minSize: 20)
    	correoElectronico(email:true,blank:false,nullable:false)
    }

    String toString(){
    	return matricula+" - "+nombreCompleto;
    }
}

Tareas/alumnos/grails-app/controllers/com/itesm/grails/alumnos/StudentController.groovy
package com.itesm.grails.alumnos

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class StudentController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
            if(params.query){
                def listAlumno =  Student.withCriteria{
                    or{
                        ilike('matricula', '%'+params.query+'%')
                        ilike('nombreCompleto', '%'+params.query+'%')
                        ilike('correoElectronico', '%'+params.query+'%')
                    }
                }
                respond  listAlumno,  model:[studentCount: listAlumno.size()] 
            }else{
                respond Student.list(params), model:[studentCount: Student.count()]
            }
    }

    def show(Student student) {
        respond student
    }

    def create() {
        respond new Student(params)
    }

    @Transactional
    def save(Student student) {
        if (student == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (student.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond student.errors, view:'create'
            return
        }



        student.save flush:true

        student.matricula=matriculaCreate(student.id)
        student.save flush:true


        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'student.label', default: 'Student'), student.id])
                redirect student
            }
            '*' { respond student, [status: CREATED] }
        }
    }

    String matriculaCreate(long id){
        String mat=""+id;
        int size=mat.length();
        if(size==7){
            return "A0"+mat;
        }else{
            int cond=7-size;
            for (int i = 0; i<cond; i++) {
               mat="0"+mat;
            }
            return "A0"+mat;
        }
    }

    def edit(Student student) {
        respond student
    }

    @Transactional
    def update(Student student) {
        if (student == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (student.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond student.errors, view:'edit'
            return
        }

        student.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'student.label', default: 'Student'), student.id])
                redirect student
            }
            '*'{ respond student, [status: OK] }
        }
    }

    @Transactional
    def delete(Student student) {

        if (student == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        student.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'student.label', default: 'Student'), student.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'student.label', default: 'Student'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Tareas/alumnos/grails-app/views/student/create.gsp
<%@ page import="com.itesm.grails.alumnos.Career"%>
<%@ page import="com.itesm.grails.alumnos.Campus"%>

<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'student.label', default: 'Alumno')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-student" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.student}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.student}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <fieldset class="form">
                    <!--<f:all bean="student"/>-->
                    <div class="fieldcontain required">
                        <label>Nombre Completo: </label>
                        <g:textField name="nombreCompleto" id="nombre" value="${student.nombreCompleto}" size="50"/>
                    </div>

                    <div class="fieldcontain required">
                        <label>Dirección: </label>
                        <g:textArea name="direccion" id="direccion" value="${student.direccion}"/>
                    </div>
                    <div class="fieldcontain required">
                        <label>Correo electrónico: </label>
                        <g:textField name="correoElectronico" id="correoElectronico" value="${student.correoElectronico}" size="30"/>
                    </div>
                    <div class="fieldcontain required">    
                        <label>Carrera: </label> <g:select name="career" from ="${Career.list()}" optionKey="id" optionValue="nombreCarrera"/>
                    </div>
                    <div class="fieldcontain required">
                        <label>Campus: </label> <g:select name="campus" from ="${Campus.list()}" optionKey="id" optionValue="nombreCampus"/>
                    </div>

                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

Tareas/alumnos/grails-app/views/student/edit.gsp
<%@ page import="com.itesm.grails.alumnos.Career"%>
<%@ page import="com.itesm.grails.alumnos.Campus"%>

<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'student.label', default: 'Alumno')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-student" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.student}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.student}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.student}" method="PUT">
                <g:hiddenField name="version" value="${this.student?.version}" />
                <fieldset class="form">

                    <div class="fieldcontain required">
                        <span id="matricula-label" class="property-label">Matricula:</span>
                        <div class="property-value" aria-labelledby="matricula-label">${student.matricula}</div>
                    </div>
                    
                    <div class="fieldcontain required">
                        <label>Nombre Completo: </label>
                        <g:textField name="nombreCompleto" id="nombre" value="${student.nombreCompleto}" size="50"/>
                    </div>

                    <div class="fieldcontain required">
                        <label>Dirección: </label>
                        <g:textArea name="direccion" id="direccion" value="${student.direccion}"/>
                    </div>
                    <div class="fieldcontain required">
                        <label>Correo electrónico: </label>
                        <g:textField name="correoElectronico" id="correoElectronico" value="${student.correoElectronico}" size="30"/>
                    </div>
                    <div class="fieldcontain required">    
                        <label>Carrera: </label> <g:select name="career" from ="${Career.list()}" optionKey="id" optionValue="nombreCarrera"/>
                    </div>
                    <div class="fieldcontain required">
                        <label>Campus: </label> <g:select name="campus" from ="${Campus.list()}" optionKey="id" optionValue="nombreCampus"/>
                    </div>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

Tareas/alumnos/grails-app/views/student/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'student.label', default: 'Alumno')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-student" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:form action="index" method="GET">
               <div class="fieldcontain">
                    <span id="query" class="property-label">Busqueda: </span>
                    <g:textField name="query" for="query" value="${params.query}" placeholder="Busqueda"/>
                    <button type="submit">Buscar</button>
                </div>
                
            </g:form>
            <f:table collection="${studentList}" />

            <div class="pagination">
                <g:paginate total="${studentCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

Tareas/alumnos/grails-app/views/student/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'student.label', default: 'Alumno')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-student" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="student" />
            <g:form resource="${this.student}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.student}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>